<%@ Page Title="" Language="C#" MasterPageFile="~/Content/ql_tour/Trangchu.master" AutoEventWireup="true" CodeFile="Thongtintourhuy.aspx.cs" Inherits="Content_ql_tour_Thongtintourhuy" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:QL_DuLichConnectionString %>" DeleteCommand="DELETE FROM ThongTinDKTour WHERE (MaKH=@MaKH)" SelectCommand="SELECT Tour.TenTour, KhachHang.TenKH, KhachHang.SDT, KhachHang.Email, KhachHang.Diachi, ThongTinDKTour.NgayDat, ThongTinDKTour.NguoiLon, ThongTinDKTour.SoTreEm, ThongTinDKTour.MaKH, ThongTinDKTour.ThanhTien FROM KhachHang INNER JOIN ThongTinDKTour ON KhachHang.MaKH = ThongTinDKTour.MaKH INNER JOIN Tour ON ThongTinDKTour.MaTour = Tour.MaTour WHERE (KhachHang.Email = @email)">
    <DeleteParameters>
        <asp:Parameter Name="MaKH" />
    </DeleteParameters>
    <SelectParameters>
        <asp:QueryStringParameter Name="email" QueryStringField="email" />
    </SelectParameters>
</asp:SqlDataSource>
    <table style="width:100%;">
        <tr>
            <td colspan="2"><asp:GridView ID="grid_ds_huy" runat="server" DataSourceID="SqlDataSource1" Width="100%" AutoGenerateDeleteButton="True" DataKeyNames="MaKH" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="grid_ds_huy_RowUpdating" AutoGenerateColumns="False">
    <Columns>
        <asp:BoundField DataField="TenTour" HeaderText="Tên tour" SortExpression="TenTour" />
        <asp:BoundField DataField="TenKH" HeaderText="Tên KH" SortExpression="TenKH" />
        <asp:BoundField DataField="SDT" HeaderText="SDT" SortExpression="SDT" />
        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
        <asp:BoundField DataField="Diachi" HeaderText="Địa chỉ" SortExpression="Diachi" />
        <asp:BoundField DataField="NgayDat" HeaderText="Ngày đặt" SortExpression="NgayDat" />
        <asp:BoundField DataField="NguoiLon" HeaderText="Số lượng người lớn" SortExpression="NguoiLon" />
        <asp:BoundField DataField="SoTreEm" HeaderText="Số lượng trẻ em" SortExpression="SoTreEm" />
        <asp:BoundField DataField="ThanhTien" HeaderText="Thành tiền" SortExpression="ThanhTien" />
    </Columns>
</asp:GridView>
            </td>
        </tr>
        <tr>
            <td style="width: 462px">&nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>

</asp:Content>

