#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_DuLich")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertChiTiet(ChiTiet instance);
  partial void UpdateChiTiet(ChiTiet instance);
  partial void DeleteChiTiet(ChiTiet instance);
  partial void InsertThongTinDKTour(ThongTinDKTour instance);
  partial void UpdateThongTinDKTour(ThongTinDKTour instance);
  partial void DeleteThongTinDKTour(ThongTinDKTour instance);
  partial void InsertKhachHang(KhachHang instance);
  partial void UpdateKhachHang(KhachHang instance);
  partial void DeleteKhachHang(KhachHang instance);
  partial void InsertNguoiDung(NguoiDung instance);
  partial void UpdateNguoiDung(NguoiDung instance);
  partial void DeleteNguoiDung(NguoiDung instance);
  partial void InsertNhanVien(NhanVien instance);
  partial void UpdateNhanVien(NhanVien instance);
  partial void DeleteNhanVien(NhanVien instance);
  partial void InsertNhomNguoiDung(NhomNguoiDung instance);
  partial void UpdateNhomNguoiDung(NhomNguoiDung instance);
  partial void DeleteNhomNguoiDung(NhomNguoiDung instance);
  partial void InsertTour(Tour instance);
  partial void UpdateTour(Tour instance);
  partial void DeleteTour(Tour instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_DuLichConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ChiTiet> ChiTiets
	{
		get
		{
			return this.GetTable<ChiTiet>();
		}
	}
	
	public System.Data.Linq.Table<ThongTinDKTour> ThongTinDKTours
	{
		get
		{
			return this.GetTable<ThongTinDKTour>();
		}
	}
	
	public System.Data.Linq.Table<KhachHang> KhachHangs
	{
		get
		{
			return this.GetTable<KhachHang>();
		}
	}
	
	public System.Data.Linq.Table<NguoiDung> NguoiDungs
	{
		get
		{
			return this.GetTable<NguoiDung>();
		}
	}
	
	public System.Data.Linq.Table<NhanVien> NhanViens
	{
		get
		{
			return this.GetTable<NhanVien>();
		}
	}
	
	public System.Data.Linq.Table<NhomNguoiDung> NhomNguoiDungs
	{
		get
		{
			return this.GetTable<NhomNguoiDung>();
		}
	}
	
	public System.Data.Linq.Table<Tour> Tours
	{
		get
		{
			return this.GetTable<Tour>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet")]
public partial class ChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaCT;
	
	private string _Hinh;
	
	private System.Nullable<System.DateTime> _NgayKhoiHanh;
	
	private string _MaTour;
	
	private string _LichTrinh;
	
	private EntityRef<Tour> _Tour;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnNgayKhoiHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhoiHanhChanged();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnLichTrinhChanging(string value);
    partial void OnLichTrinhChanged();
    #endregion
	
	public ChiTiet()
	{
		this._Tour = default(EntityRef<Tour>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaCT
	{
		get
		{
			return this._MaCT;
		}
		set
		{
			if ((this._MaCT != value))
			{
				this.OnMaCTChanging(value);
				this.SendPropertyChanging();
				this._MaCT = value;
				this.SendPropertyChanged("MaCT");
				this.OnMaCTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="VarChar(50)")]
	public string Hinh
	{
		get
		{
			return this._Hinh;
		}
		set
		{
			if ((this._Hinh != value))
			{
				this.OnHinhChanging(value);
				this.SendPropertyChanging();
				this._Hinh = value;
				this.SendPropertyChanged("Hinh");
				this.OnHinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiHanh", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayKhoiHanh
	{
		get
		{
			return this._NgayKhoiHanh;
		}
		set
		{
			if ((this._NgayKhoiHanh != value))
			{
				this.OnNgayKhoiHanhChanging(value);
				this.SendPropertyChanging();
				this._NgayKhoiHanh = value;
				this.SendPropertyChanged("NgayKhoiHanh");
				this.OnNgayKhoiHanhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="VarChar(10)")]
	public string MaTour
	{
		get
		{
			return this._MaTour;
		}
		set
		{
			if ((this._MaTour != value))
			{
				if (this._Tour.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaTourChanging(value);
				this.SendPropertyChanging();
				this._MaTour = value;
				this.SendPropertyChanged("MaTour");
				this.OnMaTourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LichTrinh", DbType="NVarChar(1000)")]
	public string LichTrinh
	{
		get
		{
			return this._LichTrinh;
		}
		set
		{
			if ((this._LichTrinh != value))
			{
				this.OnLichTrinhChanging(value);
				this.SendPropertyChanging();
				this._LichTrinh = value;
				this.SendPropertyChanged("LichTrinh");
				this.OnLichTrinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_ChiTiet", Storage="_Tour", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
	public Tour Tour
	{
		get
		{
			return this._Tour.Entity;
		}
		set
		{
			Tour previousValue = this._Tour.Entity;
			if (((previousValue != value) 
						|| (this._Tour.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Tour.Entity = null;
					previousValue.ChiTiets.Remove(this);
				}
				this._Tour.Entity = value;
				if ((value != null))
				{
					value.ChiTiets.Add(this);
					this._MaTour = value.MaTour;
				}
				else
				{
					this._MaTour = default(string);
				}
				this.SendPropertyChanged("Tour");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinDKTour")]
public partial class ThongTinDKTour : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Nullable<System.DateTime> _NgayDat;
	
	private System.Nullable<int> _NguoiLon;
	
	private System.Nullable<int> _SoTreEm;
	
	private string _MaKH;
	
	private string _MaTour;
	
	private System.Nullable<double> _ThanhTien;
	
	private EntitySet<KhachHang> _KhachHangs;
	
	private EntityRef<Tour> _Tour;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNguoiLonChanging(System.Nullable<int> value);
    partial void OnNguoiLonChanged();
    partial void OnSoTreEmChanging(System.Nullable<int> value);
    partial void OnSoTreEmChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    #endregion
	
	public ThongTinDKTour()
	{
		this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
		this._Tour = default(EntityRef<Tour>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayDat
	{
		get
		{
			return this._NgayDat;
		}
		set
		{
			if ((this._NgayDat != value))
			{
				this.OnNgayDatChanging(value);
				this.SendPropertyChanging();
				this._NgayDat = value;
				this.SendPropertyChanged("NgayDat");
				this.OnNgayDatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLon", DbType="Int")]
	public System.Nullable<int> NguoiLon
	{
		get
		{
			return this._NguoiLon;
		}
		set
		{
			if ((this._NguoiLon != value))
			{
				this.OnNguoiLonChanging(value);
				this.SendPropertyChanging();
				this._NguoiLon = value;
				this.SendPropertyChanged("NguoiLon");
				this.OnNguoiLonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTreEm", DbType="Int")]
	public System.Nullable<int> SoTreEm
	{
		get
		{
			return this._SoTreEm;
		}
		set
		{
			if ((this._SoTreEm != value))
			{
				this.OnSoTreEmChanging(value);
				this.SendPropertyChanging();
				this._SoTreEm = value;
				this.SendPropertyChanged("SoTreEm");
				this.OnSoTreEmChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaKH
	{
		get
		{
			return this._MaKH;
		}
		set
		{
			if ((this._MaKH != value))
			{
				this.OnMaKHChanging(value);
				this.SendPropertyChanging();
				this._MaKH = value;
				this.SendPropertyChanged("MaKH");
				this.OnMaKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="VarChar(10)")]
	public string MaTour
	{
		get
		{
			return this._MaTour;
		}
		set
		{
			if ((this._MaTour != value))
			{
				if (this._Tour.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaTourChanging(value);
				this.SendPropertyChanging();
				this._MaTour = value;
				this.SendPropertyChanged("MaTour");
				this.OnMaTourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
	public System.Nullable<double> ThanhTien
	{
		get
		{
			return this._ThanhTien;
		}
		set
		{
			if ((this._ThanhTien != value))
			{
				this.OnThanhTienChanging(value);
				this.SendPropertyChanging();
				this._ThanhTien = value;
				this.SendPropertyChanged("ThanhTien");
				this.OnThanhTienChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinDKTour_KhachHang", Storage="_KhachHangs", ThisKey="MaKH", OtherKey="MaKH")]
	public EntitySet<KhachHang> KhachHangs
	{
		get
		{
			return this._KhachHangs;
		}
		set
		{
			this._KhachHangs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_ThongTinDKTour", Storage="_Tour", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
	public Tour Tour
	{
		get
		{
			return this._Tour.Entity;
		}
		set
		{
			Tour previousValue = this._Tour.Entity;
			if (((previousValue != value) 
						|| (this._Tour.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Tour.Entity = null;
					previousValue.ThongTinDKTours.Remove(this);
				}
				this._Tour.Entity = value;
				if ((value != null))
				{
					value.ThongTinDKTours.Add(this);
					this._MaTour = value.MaTour;
				}
				else
				{
					this._MaTour = default(string);
				}
				this.SendPropertyChanged("Tour");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_KhachHangs(KhachHang entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinDKTour = this;
	}
	
	private void detach_KhachHangs(KhachHang entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinDKTour = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaKH;
	
	private string _TenKH;
	
	private System.Nullable<System.DateTime> _NgaySinh;
	
	private string _GioiTinh;
	
	private string _SDT;
	
	private string _Email;
	
	private string _Diachi;
	
	private string _CMND;
	
	private int _STT;
	
	private EntityRef<ThongTinDKTour> _ThongTinDKTour;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    #endregion
	
	public KhachHang()
	{
		this._ThongTinDKTour = default(EntityRef<ThongTinDKTour>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(10)")]
	public string MaKH
	{
		get
		{
			return this._MaKH;
		}
		set
		{
			if ((this._MaKH != value))
			{
				if (this._ThongTinDKTour.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaKHChanging(value);
				this.SendPropertyChanging();
				this._MaKH = value;
				this.SendPropertyChanged("MaKH");
				this.OnMaKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(30)")]
	public string TenKH
	{
		get
		{
			return this._TenKH;
		}
		set
		{
			if ((this._TenKH != value))
			{
				this.OnTenKHChanging(value);
				this.SendPropertyChanging();
				this._TenKH = value;
				this.SendPropertyChanged("TenKH");
				this.OnTenKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgaySinh
	{
		get
		{
			return this._NgaySinh;
		}
		set
		{
			if ((this._NgaySinh != value))
			{
				this.OnNgaySinhChanging(value);
				this.SendPropertyChanging();
				this._NgaySinh = value;
				this.SendPropertyChanged("NgaySinh");
				this.OnNgaySinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
	public string GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
	public string SDT
	{
		get
		{
			return this._SDT;
		}
		set
		{
			if ((this._SDT != value))
			{
				this.OnSDTChanging(value);
				this.SendPropertyChanging();
				this._SDT = value;
				this.SendPropertyChanged("SDT");
				this.OnSDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
	public string Diachi
	{
		get
		{
			return this._Diachi;
		}
		set
		{
			if ((this._Diachi != value))
			{
				this.OnDiachiChanging(value);
				this.SendPropertyChanging();
				this._Diachi = value;
				this.SendPropertyChanged("Diachi");
				this.OnDiachiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(20)")]
	public string CMND
	{
		get
		{
			return this._CMND;
		}
		set
		{
			if ((this._CMND != value))
			{
				this.OnCMNDChanging(value);
				this.SendPropertyChanging();
				this._CMND = value;
				this.SendPropertyChanged("CMND");
				this.OnCMNDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int STT
	{
		get
		{
			return this._STT;
		}
		set
		{
			if ((this._STT != value))
			{
				this.OnSTTChanging(value);
				this.SendPropertyChanging();
				this._STT = value;
				this.SendPropertyChanged("STT");
				this.OnSTTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinDKTour_KhachHang", Storage="_ThongTinDKTour", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
	public ThongTinDKTour ThongTinDKTour
	{
		get
		{
			return this._ThongTinDKTour.Entity;
		}
		set
		{
			ThongTinDKTour previousValue = this._ThongTinDKTour.Entity;
			if (((previousValue != value) 
						|| (this._ThongTinDKTour.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ThongTinDKTour.Entity = null;
					previousValue.KhachHangs.Remove(this);
				}
				this._ThongTinDKTour.Entity = value;
				if ((value != null))
				{
					value.KhachHangs.Add(this);
					this._MaKH = value.MaKH;
				}
				else
				{
					this._MaKH = default(string);
				}
				this.SendPropertyChanged("ThongTinDKTour");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _TenDN;
	
	private string _MatKhau;
	
	private System.Nullable<bool> _HoatDong;
	
	private string _MaNh;
	
	private EntitySet<NhanVien> _NhanViens;
	
	private EntityRef<NhomNguoiDung> _NhomNguoiDung;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoatDongChanging(System.Nullable<bool> value);
    partial void OnHoatDongChanged();
    partial void OnMaNhChanging(string value);
    partial void OnMaNhChanged();
    #endregion
	
	public NguoiDung()
	{
		this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
		this._NhomNguoiDung = default(EntityRef<NhomNguoiDung>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TenDN
	{
		get
		{
			return this._TenDN;
		}
		set
		{
			if ((this._TenDN != value))
			{
				this.OnTenDNChanging(value);
				this.SendPropertyChanging();
				this._TenDN = value;
				this.SendPropertyChanged("TenDN");
				this.OnTenDNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(20)")]
	public string MatKhau
	{
		get
		{
			return this._MatKhau;
		}
		set
		{
			if ((this._MatKhau != value))
			{
				this.OnMatKhauChanging(value);
				this.SendPropertyChanging();
				this._MatKhau = value;
				this.SendPropertyChanged("MatKhau");
				this.OnMatKhauChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong", DbType="Bit")]
	public System.Nullable<bool> HoatDong
	{
		get
		{
			return this._HoatDong;
		}
		set
		{
			if ((this._HoatDong != value))
			{
				this.OnHoatDongChanging(value);
				this.SendPropertyChanging();
				this._HoatDong = value;
				this.SendPropertyChanged("HoatDong");
				this.OnHoatDongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNh", DbType="VarChar(10)")]
	public string MaNh
	{
		get
		{
			return this._MaNh;
		}
		set
		{
			if ((this._MaNh != value))
			{
				if (this._NhomNguoiDung.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaNhChanging(value);
				this.SendPropertyChanging();
				this._MaNh = value;
				this.SendPropertyChanged("MaNh");
				this.OnMaNhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NhanVien", Storage="_NhanViens", ThisKey="TenDN", OtherKey="TenDN")]
	public EntitySet<NhanVien> NhanViens
	{
		get
		{
			return this._NhanViens;
		}
		set
		{
			this._NhanViens.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_NguoiDung", Storage="_NhomNguoiDung", ThisKey="MaNh", OtherKey="MaNhom", IsForeignKey=true)]
	public NhomNguoiDung NhomNguoiDung
	{
		get
		{
			return this._NhomNguoiDung.Entity;
		}
		set
		{
			NhomNguoiDung previousValue = this._NhomNguoiDung.Entity;
			if (((previousValue != value) 
						|| (this._NhomNguoiDung.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._NhomNguoiDung.Entity = null;
					previousValue.NguoiDungs.Remove(this);
				}
				this._NhomNguoiDung.Entity = value;
				if ((value != null))
				{
					value.NguoiDungs.Add(this);
					this._MaNh = value.MaNhom;
				}
				else
				{
					this._MaNh = default(string);
				}
				this.SendPropertyChanged("NhomNguoiDung");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_NhanViens(NhanVien entity)
	{
		this.SendPropertyChanging();
		entity.NguoiDung = this;
	}
	
	private void detach_NhanViens(NhanVien entity)
	{
		this.SendPropertyChanging();
		entity.NguoiDung = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaNV;
	
	private string _TenNV;
	
	private System.Nullable<System.DateTime> _NgSinh;
	
	private string _GioiTinh;
	
	private string _CMND;
	
	private string _Dchi;
	
	private string _SoDienThoai;
	
	private string _TenDN;
	
	private EntitySet<Tour> _Tours;
	
	private EntityRef<NguoiDung> _NguoiDung;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnNgSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgSinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnDchiChanging(string value);
    partial void OnDchiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    #endregion
	
	public NhanVien()
	{
		this._Tours = new EntitySet<Tour>(new Action<Tour>(this.attach_Tours), new Action<Tour>(this.detach_Tours));
		this._NguoiDung = default(EntityRef<NguoiDung>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNV
	{
		get
		{
			return this._MaNV;
		}
		set
		{
			if ((this._MaNV != value))
			{
				this.OnMaNVChanging(value);
				this.SendPropertyChanging();
				this._MaNV = value;
				this.SendPropertyChanged("MaNV");
				this.OnMaNVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30)")]
	public string TenNV
	{
		get
		{
			return this._TenNV;
		}
		set
		{
			if ((this._TenNV != value))
			{
				this.OnTenNVChanging(value);
				this.SendPropertyChanging();
				this._TenNV = value;
				this.SendPropertyChanged("TenNV");
				this.OnTenNVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgSinh", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgSinh
	{
		get
		{
			return this._NgSinh;
		}
		set
		{
			if ((this._NgSinh != value))
			{
				this.OnNgSinhChanging(value);
				this.SendPropertyChanging();
				this._NgSinh = value;
				this.SendPropertyChanged("NgSinh");
				this.OnNgSinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(5)")]
	public string GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(12)")]
	public string CMND
	{
		get
		{
			return this._CMND;
		}
		set
		{
			if ((this._CMND != value))
			{
				this.OnCMNDChanging(value);
				this.SendPropertyChanging();
				this._CMND = value;
				this.SendPropertyChanged("CMND");
				this.OnCMNDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dchi", DbType="NVarChar(100)")]
	public string Dchi
	{
		get
		{
			return this._Dchi;
		}
		set
		{
			if ((this._Dchi != value))
			{
				this.OnDchiChanging(value);
				this.SendPropertyChanging();
				this._Dchi = value;
				this.SendPropertyChanged("Dchi");
				this.OnDchiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(10)")]
	public string SoDienThoai
	{
		get
		{
			return this._SoDienThoai;
		}
		set
		{
			if ((this._SoDienThoai != value))
			{
				this.OnSoDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._SoDienThoai = value;
				this.SendPropertyChanged("SoDienThoai");
				this.OnSoDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(20)")]
	public string TenDN
	{
		get
		{
			return this._TenDN;
		}
		set
		{
			if ((this._TenDN != value))
			{
				if (this._NguoiDung.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTenDNChanging(value);
				this.SendPropertyChanging();
				this._TenDN = value;
				this.SendPropertyChanged("TenDN");
				this.OnTenDNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Tour", Storage="_Tours", ThisKey="MaNV", OtherKey="MaNV")]
	public EntitySet<Tour> Tours
	{
		get
		{
			return this._Tours;
		}
		set
		{
			this._Tours.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NhanVien", Storage="_NguoiDung", ThisKey="TenDN", OtherKey="TenDN", IsForeignKey=true)]
	public NguoiDung NguoiDung
	{
		get
		{
			return this._NguoiDung.Entity;
		}
		set
		{
			NguoiDung previousValue = this._NguoiDung.Entity;
			if (((previousValue != value) 
						|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._NguoiDung.Entity = null;
					previousValue.NhanViens.Remove(this);
				}
				this._NguoiDung.Entity = value;
				if ((value != null))
				{
					value.NhanViens.Add(this);
					this._TenDN = value.TenDN;
				}
				else
				{
					this._TenDN = default(string);
				}
				this.SendPropertyChanged("NguoiDung");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Tours(Tour entity)
	{
		this.SendPropertyChanging();
		entity.NhanVien = this;
	}
	
	private void detach_Tours(Tour entity)
	{
		this.SendPropertyChanging();
		entity.NhanVien = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomNguoiDung")]
public partial class NhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaNhom;
	
	private string _TenNhom;
	
	private System.Nullable<bool> _IsAdmin;
	
	private EntitySet<NguoiDung> _NguoiDungs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnIsAdminChanging(System.Nullable<bool> value);
    partial void OnIsAdminChanged();
    #endregion
	
	public NhomNguoiDung()
	{
		this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNhom
	{
		get
		{
			return this._MaNhom;
		}
		set
		{
			if ((this._MaNhom != value))
			{
				this.OnMaNhomChanging(value);
				this.SendPropertyChanging();
				this._MaNhom = value;
				this.SendPropertyChanged("MaNhom");
				this.OnMaNhomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(30)")]
	public string TenNhom
	{
		get
		{
			return this._TenNhom;
		}
		set
		{
			if ((this._TenNhom != value))
			{
				this.OnTenNhomChanging(value);
				this.SendPropertyChanging();
				this._TenNhom = value;
				this.SendPropertyChanged("TenNhom");
				this.OnTenNhomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit")]
	public System.Nullable<bool> IsAdmin
	{
		get
		{
			return this._IsAdmin;
		}
		set
		{
			if ((this._IsAdmin != value))
			{
				this.OnIsAdminChanging(value);
				this.SendPropertyChanging();
				this._IsAdmin = value;
				this.SendPropertyChanged("IsAdmin");
				this.OnIsAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_NguoiDung", Storage="_NguoiDungs", ThisKey="MaNhom", OtherKey="MaNh")]
	public EntitySet<NguoiDung> NguoiDungs
	{
		get
		{
			return this._NguoiDungs;
		}
		set
		{
			this._NguoiDungs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_NguoiDungs(NguoiDung entity)
	{
		this.SendPropertyChanging();
		entity.NhomNguoiDung = this;
	}
	
	private void detach_NguoiDungs(NguoiDung entity)
	{
		this.SendPropertyChanging();
		entity.NhomNguoiDung = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tour")]
public partial class Tour : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaTour;
	
	private string _TenTour;
	
	private string _LoaiTour;
	
	private string _SoNgay;
	
	private double _GiaTour;
	
	private string _MaNV;
	
	private System.Nullable<int> _SoLuong;
	
	private EntitySet<ChiTiet> _ChiTiets;
	
	private EntitySet<ThongTinDKTour> _ThongTinDKTours;
	
	private EntityRef<NhanVien> _NhanVien;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(string value);
    partial void OnMaTourChanged();
    partial void OnTenTourChanging(string value);
    partial void OnTenTourChanged();
    partial void OnLoaiTourChanging(string value);
    partial void OnLoaiTourChanged();
    partial void OnSoNgayChanging(string value);
    partial void OnSoNgayChanged();
    partial void OnGiaTourChanging(double value);
    partial void OnGiaTourChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
	
	public Tour()
	{
		this._ChiTiets = new EntitySet<ChiTiet>(new Action<ChiTiet>(this.attach_ChiTiets), new Action<ChiTiet>(this.detach_ChiTiets));
		this._ThongTinDKTours = new EntitySet<ThongTinDKTour>(new Action<ThongTinDKTour>(this.attach_ThongTinDKTours), new Action<ThongTinDKTour>(this.detach_ThongTinDKTours));
		this._NhanVien = default(EntityRef<NhanVien>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaTour
	{
		get
		{
			return this._MaTour;
		}
		set
		{
			if ((this._MaTour != value))
			{
				this.OnMaTourChanging(value);
				this.SendPropertyChanging();
				this._MaTour = value;
				this.SendPropertyChanged("MaTour");
				this.OnMaTourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTour", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string TenTour
	{
		get
		{
			return this._TenTour;
		}
		set
		{
			if ((this._TenTour != value))
			{
				this.OnTenTourChanging(value);
				this.SendPropertyChanging();
				this._TenTour = value;
				this.SendPropertyChanged("TenTour");
				this.OnTenTourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTour", DbType="NVarChar(50)")]
	public string LoaiTour
	{
		get
		{
			return this._LoaiTour;
		}
		set
		{
			if ((this._LoaiTour != value))
			{
				this.OnLoaiTourChanging(value);
				this.SendPropertyChanging();
				this._LoaiTour = value;
				this.SendPropertyChanged("LoaiTour");
				this.OnLoaiTourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgay", DbType="NVarChar(50)")]
	public string SoNgay
	{
		get
		{
			return this._SoNgay;
		}
		set
		{
			if ((this._SoNgay != value))
			{
				this.OnSoNgayChanging(value);
				this.SendPropertyChanging();
				this._SoNgay = value;
				this.SendPropertyChanged("SoNgay");
				this.OnSoNgayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTour", DbType="Float NOT NULL")]
	public double GiaTour
	{
		get
		{
			return this._GiaTour;
		}
		set
		{
			if ((this._GiaTour != value))
			{
				this.OnGiaTourChanging(value);
				this.SendPropertyChanging();
				this._GiaTour = value;
				this.SendPropertyChanged("GiaTour");
				this.OnGiaTourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(10)")]
	public string MaNV
	{
		get
		{
			return this._MaNV;
		}
		set
		{
			if ((this._MaNV != value))
			{
				if (this._NhanVien.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaNVChanging(value);
				this.SendPropertyChanging();
				this._MaNV = value;
				this.SendPropertyChanged("MaNV");
				this.OnMaNVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_ChiTiet", Storage="_ChiTiets", ThisKey="MaTour", OtherKey="MaTour")]
	public EntitySet<ChiTiet> ChiTiets
	{
		get
		{
			return this._ChiTiets;
		}
		set
		{
			this._ChiTiets.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_ThongTinDKTour", Storage="_ThongTinDKTours", ThisKey="MaTour", OtherKey="MaTour")]
	public EntitySet<ThongTinDKTour> ThongTinDKTours
	{
		get
		{
			return this._ThongTinDKTours;
		}
		set
		{
			this._ThongTinDKTours.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Tour", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
	public NhanVien NhanVien
	{
		get
		{
			return this._NhanVien.Entity;
		}
		set
		{
			NhanVien previousValue = this._NhanVien.Entity;
			if (((previousValue != value) 
						|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._NhanVien.Entity = null;
					previousValue.Tours.Remove(this);
				}
				this._NhanVien.Entity = value;
				if ((value != null))
				{
					value.Tours.Add(this);
					this._MaNV = value.MaNV;
				}
				else
				{
					this._MaNV = default(string);
				}
				this.SendPropertyChanged("NhanVien");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ChiTiets(ChiTiet entity)
	{
		this.SendPropertyChanging();
		entity.Tour = this;
	}
	
	private void detach_ChiTiets(ChiTiet entity)
	{
		this.SendPropertyChanging();
		entity.Tour = null;
	}
	
	private void attach_ThongTinDKTours(ThongTinDKTour entity)
	{
		this.SendPropertyChanging();
		entity.Tour = this;
	}
	
	private void detach_ThongTinDKTours(ThongTinDKTour entity)
	{
		this.SendPropertyChanging();
		entity.Tour = null;
	}
}
#pragma warning restore 1591
